/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject4;

/**
 *
 * @author OWNER
 */
public class mouseevent extends javax.swing.JFrame {

    /**
     * Creates new form mouseevent
     */
    public mouseevent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                l2mouse2(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l5mouse5(evt);
            }
        });
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                l8mouse8(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1mouse1(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l3mouse3(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l4mouse4(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l6mouse6(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                l7mouse7(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                l6window6(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                l8window8(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                l0window10(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                l1widow1(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                l2window2(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                l3window3(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                l4window4(evt);
            }
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                l5window5(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                l7window7(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                l9window9(evt);
            }
        });

        l1.setText("labe1");

        l2.setText("label2");

        l3.setText("label3");

        l4.setText("label4");

        l5.setText("label5");

        l6.setText("label6");

        l7.setText("label7");

        l8.setText("label8");

        jLabel1.setText("label1");

        jLabel3.setText("label2");

        jLabel2.setText("l3");

        jLabel4.setText("Label4");

        jLabel5.setText("Label5");

        jLabel6.setText("Label6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(l1)
                .addGap(18, 18, 18)
                .addComponent(l2)
                .addGap(35, 35, 35)
                .addComponent(l3)
                .addGap(15, 15, 15)
                .addComponent(l4)
                .addGap(27, 27, 27)
                .addComponent(l5)
                .addGap(18, 18, 18)
                .addComponent(l6)
                .addGap(18, 18, 18)
                .addComponent(l7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l8)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l2mouse2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2mouse2
      l2.setText("i");
        
    }//GEN-LAST:event_l2mouse2

    private void l1mouse1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1mouse1
        l1.setText("hello gugs.....");
    }//GEN-LAST:event_l1mouse1

    private void l3mouse3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3mouse3
       l3.setText("am");
    }//GEN-LAST:event_l3mouse3

    private void l4mouse4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4mouse4
      l4.setText("amalu");
    }//GEN-LAST:event_l4mouse4

    private void l5mouse5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5mouse5
        l5.setText("jose");
    }//GEN-LAST:event_l5mouse5

    private void l6mouse6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6mouse6
       l6.setText("A");
    }//GEN-LAST:event_l6mouse6

    private void l7mouse7(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7mouse7
         l7.setText("mca student");
    }//GEN-LAST:event_l7mouse7

    private void l8mouse8(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_l8mouse8
        l8.setText("thanku for opening");
    }//GEN-LAST:event_l8mouse8

    private void l1widow1(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l1widow1
       jLabel1.setText("hello");
    }//GEN-LAST:event_l1widow1

    private void l2window2(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l2window2
       jLabel2.setText("i am");
    }//GEN-LAST:event_l2window2

    private void l3window3(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l3window3
        jLabel3.setText("amalu jose");
    }//GEN-LAST:event_l3window3

    private void l4window4(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l4window4
       jLabel4.setText("njan ");
    }//GEN-LAST:event_l4window4

    private void l5window5(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l5window5
      jLabel5.setText("solliye avanam");
    }//GEN-LAST:event_l5window5

    private void l6window6(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l6window6
        jLabel6.setText("ni");
    }//GEN-LAST:event_l6window6

    private void l7window7(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l7window7
        jLabel7.setText("avalom");
    }//GEN-LAST:event_l7window7

    private void l8window8(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l8window8
        jLabel8.setText("azhagu");
    }//GEN-LAST:event_l8window8

    private void l9window9(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l9window9
        jLabel9.setText("smile");
    }//GEN-LAST:event_l9window9

    private void l0window10(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_l0window10
      jLabel10.setText("please");
    }//GEN-LAST:event_l0window10

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mouseevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mouseevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mouseevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mouseevent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mouseevent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    // End of variables declaration//GEN-END:variables
}
